// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"KMS_AltGauge","status":true,"description":"[v0.2.0] Display alternative gauge.","parameters":{"HP gauge image":"GaugeHP","HP gauge config":"-31, -2, -4, 30","MP gauge image":"GaugeMP","MP gauge config":"-31, -2, -4, 30","TP gauge image":"GaugeTP","TP gauge config":"-31, -2, -4, 30","EXP gauge image":"GaugeEXP","EXP gauge config":"-31, -2, -4, 30","Use exp gauge":"1"}},
{"name":"TestParameter02","status":true,"description":"","parameters":{"Id開關":"0"}},
{"name":"TestClass","status":true,"description":"","parameters":{}},
{"name":"TestGlobalParameter","status":true,"description":"","parameters":{}},
{"name":"battle_windows","status":true,"description":"","parameters":{}}
];
